package com.example.myfirstapp;

import android.content.Intent;
import android.support.v7.app.AppCompatActivity;
import android.os.Bundle;
import android.view.ViewGroup;
import android.widget.TextView;

public class DisplayMessageActivity extends AppCompatActivity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_display_message);

        Intent intent = getIntent();
        String message = intent.getStringExtra(MainActivity.EXTRA_MESSAGE);
        TextView textView = new TextView(this);
        textView.setTextSize(140);
        textView.setText(message);

        ViewGroup layout = (ViewGroup) findViewById(R.id.activity_display_message);
        layout.addView((textView));
    }
}

    /*

    The call getIntent() grabs the intent that started the activity. Every Activity is invoked
    by an Intent, regardless of how the user navigated there. The call getStringExtra() retrieves
    the data from the first activity.

    You programmatically create a TextView and set its size and message.

    You add the TextView to the layout identified by R.id.activity_display_message. You cast the
    layout to ViewGroup because it is the superclass of all layouts and contains the addView()
    method.

    Note: The XML layout generated by previous versions of Android Studio might
    not include the android:id attribute. The call findViewById() will fail if the layout does not
    have the android:id attribute. If this is the case, open activity_display_message.xml and add
    the attribute android:id="@+id/activity_display_message" to the layout element. (This applied
    to me, at the time of development I was using Android Studio v2.1.3)

    */

